// MCP server instructions are quite unreliable in practice (many clients drop them entirely, at least I know OpenCode does), so here we keep the server instructions concise and short. All necessary details are included in the per-tool descriptions.
export const SERVER_INSTRUCTIONS = [
  "This server exposes three tools and one prompt:",
  "- parse_tags: always-on prompt expander. Call this every turn on the user's verbatim prompt before doing other work; if `#tag-name` markers appear in the rewritten output as `<name/>` placeholders with `<name>...body...</name>` blocks at the top, treat those bodies as authoritative directives and follow them at the location each `<name/>` appears.",
  "- list_tags: read-only inventory. Call when you need to know which tags are currently defined (e.g. user asks 'what tags do I have', or you suspect an unexpected miss). Each entry is annotated with its origin: 'builtin' | 'global' | 'workspace'. Workspace overrides global, which overrides builtin.",
  "- show_tag: inspect a single tag's body for verification or debugging. Use list_tags first if you don't know the name.",
  "- create-tag-guide prompt: user-controlled guide for creating or editing `.agents/tags/*.md` files. Use prompts/list and prompts/get to retrieve it when the user asks for tag-authoring help.",
  "",
  "Calling rules:",
  "- Recognize `#tag-name` (or `#tag_name`) as a syntactic marker that requires parse_tags. You do not need to know the tag inventory in advance; unknown names pass through unchanged.",
  "- The `workspace` argument on parse_tags / list_tags / show_tag is optional. When omitted, the server uses the workspace it was launched in. Pass an explicit absolute path only when the user is operating on a different project root.",
  "- The tag set is dynamic. Tag definitions live under `~/.agents/tags` (global) and `<workspace>/.agents/tags` (project) and can change between turns. The MCP tool descriptions are intentionally static — query list_tags / show_tag at runtime instead of relying on a baked-in inventory.",
  "",
  "Note: some MCP clients drop this instructions field. The per-tool descriptions therefore restate each tool's contract, but the live tag inventory is only available via list_tags / show_tag.",
].join("\n");

export const PARSE_TAGS_DESCRIPTION = [
  'Expand inline `#tag` markers (e.g. `#explore`, `#fyi`, `#example`, `#btw`, `#deny`) in a user prompt into XML directives. For each recognized `#name` in prose, the tool injects `<name>...body...</name>` once at the top of the rewritten prompt and replaces each `#name` with a self-closing `<name/>` at its original location. The marker can sit anywhere — opening (`#btw the previous...`), middle (`...handles `#tag_name` resolution...`), end (`...check the regex specifics #explore`), or scattered across multiple clauses. Tags inside fenced code blocks (```) and inline code spans (`) are preserved verbatim. Unknown `#tags` (no matching definition) pass through unchanged. `#tag_name` and `#tag-name` resolve to the same definition. Returns the literal sentinel "(no tags found)" when no recognized `#tag` markers appear in prose.',
  "",
  "EXAMPLES:",
  "",
  "  user: ok thanks, continue",
  '  call: parse_tags({ prompt: "ok thanks, continue" })',
  "  result: (no tags found)",
  "",
  "  user: walk me through how the prompt rewriter handles edge cases #explore",
  '  call: parse_tags({ prompt: "walk me through how the prompt rewriter handles edge cases #explore" })',
  "  result:",
  "    <explore>...explore body...</explore>",
  "",
  "    walk me through how the prompt rewriter handles edge cases <explore/>",
  "",
  "  user: explain how this server discovers tag definitions",
  '  call: parse_tags({ prompt: "explain how this server discovers tag definitions" })',
  "  result: (no tags found)",
  "",
  "  user: what's the #deny tag for?",
  '  call: parse_tags({ prompt: "what\'s the #deny tag for?" })',
  "  result:",
  "    <deny>...deny body...</deny>",
  "",
  "    what's the <deny/> tag for?",
  "",
  "  user: Compare FilesystemTagSource and MergedTagSource #explore. The merging behavior #fyi is intentional.",
  '  call: parse_tags({ prompt: "Compare FilesystemTagSource and MergedTagSource #explore. The merging behavior #fyi is intentional." })',
  "  result:",
  "    <explore>...explore body...</explore>",
  "    <fyi>...fyi body...</fyi>",
  "",
  "    Compare FilesystemTagSource and MergedTagSource <explore/>. The merging behavior <fyi/> is intentional.",
  "",
  "  user: just answer directly, no tools — what's the difference between #fyi and #btw?",
  '  call: parse_tags({ prompt: "just answer directly, no tools — what\'s the difference between #fyi and #btw?" })',
  "  result:",
  "    <fyi>...fyi body...</fyi>",
  "    <btw>...btw body...</btw>",
  "",
  "    just answer directly, no tools — what's the difference between <fyi/> and <btw/>?",
  "",
  "  user: add a tag for discarding objects (file/function/modules etc. #example)",
  '  call: parse_tags({ prompt: "add a tag for discarding objects (file/function/modules etc. #example)" })',
  "  result:",
  "    <example>...example body...</example>",
  "",
  "    add a tag for discarding objects (file/function/modules etc. <example/>)",
  "",
  "  user (code fence with tag inside):",
  "    ```",
  "    # comment containing #fyi",
  "    ```",
  "    what does the snippet do?",
  "  call: parse_tags({ prompt: <verbatim including the code fence> })",
  "  result: (no tags found)        # tags inside code fences are escape hatches, not directives",
  "",
  "  user: explain the `TAG_REGEX` const, reference it with #explore",
  '  call: parse_tags({ prompt: "explain the `TAG_REGEX` const, reference it with #explore" })',
  "  result:",
  "    <explore>...explore body...</explore>",
  "",
  "    explain the `TAG_REGEX` const, reference it with <explore/>",
  "",
  "  user: I want to use #somemadeuptagname here",
  '  call: parse_tags({ prompt: "I want to use #somemadeuptagname here" })',
  "  result: I want to use #somemadeuptagname here     # unknown tag passes through unchanged, no header injected",
  "",
  "  user: in promptRewriter.ts, what's the difference between how line 70 detects fenced code blocks versus how line 96 detects inline backticks? include the regex/string-matching specifics #explore",
  '  call: parse_tags({ prompt: "in promptRewriter.ts, what\'s the difference between how line 70 detects fenced code blocks versus how line 96 detects inline backticks? include the regex/string-matching specifics #explore" })',
  "  result:",
  "    <explore>...explore body...</explore>",
  "",
  "    in promptRewriter.ts, what's the difference between how line 70 detects fenced code blocks versus how line 96 detects inline backticks? include the regex/string-matching specifics <explore/>",
  "  # long, technically dense prompts still get parsed first — the visual weight of the question doesn't change the routine",
  "",
  "  user: #btw the previous test session was useful — now show me how `BuiltinTagSource` is wired into the merged source chain, and infer where future remote sources would plug in #example",
  '  call: parse_tags({ prompt: "#btw the previous test session was useful — now show me how `BuiltinTagSource` is wired into the merged source chain, and infer where future remote sources would plug in #example" })',
  "  result:",
  "    <btw>...btw body...</btw>",
  "    <example>...example body...</example>",
  "",
  "    <btw/> the previous test session was useful — now show me how `BuiltinTagSource` is wired into the merged source chain, and infer where future remote sources would plug in <example/>",
  "  # multiple tags across one prompt are all parsed in a single call; conversational lead-ins (`#btw`) and substantive directives (`#example`) coexist",
  "",
  "  user: now look at how `MergedTagSource.get()` resolves collisions between global and workspace tags, then explain why `BuiltinTagSource` ends up at the start of the source array even though it's the lowest precedence #explore",
  '  call: parse_tags({ prompt: "now look at how `MergedTagSource.get()` resolves collisions between global and workspace tags, then explain why `BuiltinTagSource` ends up at the start of the source array even though it\'s the lowest precedence #explore" })',
  "  result:",
  "    <explore>...explore body...</explore>",
  "",
  "    now look at how `MergedTagSource.get()` resolves collisions between global and workspace tags, then explain why `BuiltinTagSource` ends up at the start of the source array even though it's the lowest precedence <explore/>",
  "  # multi-clause technical asks with a trailing tag still trigger the call before any code is read; the routine fires regardless of how the prompt opens",
  "",
  "INPUTS:",
  "- prompt: the user's verbatim message for the turn. Pass it unmodified — the rewriter relies on the literal text, including code fences and inline code spans, to decide what to expand and what to preserve.",
  "- workspace (optional): absolute path to the user's project root. Used to load workspace-scoped tag definitions (which override global tags on name collision). When omitted, the server-startup workspace is used.",
  "",
  "OUTPUT:",
  "- For tag-bearing prompts: the rewritten prompt with `<name>...body...</name>` directive blocks prepended and `<name/>` placeholders in prose at the original locations. Each `<name/>` directive applies at the location it appears, not globally.",
  '- For tag-free prompts: the literal sentinel string "(no tags found)".',
  "- For prompts with only unknown `#tags`: the prompt is returned unchanged, with the `#name` markers preserved verbatim.",
  "",
  "BOUNDARY:",
  "- The tool's rewritten output is the single source of truth for tag bodies. Read the injected `<name>...body...</name>` content rather than guessing what each `#name` means based on its label alone.",
  "- The presence, position, or visual weight of a `#tag` does not change the routine — `#explore` at the end of a long technical question, `#btw` opening a casual aside, `#fyi` mid-clause, and `#somemadeup` (unknown) all flow through the same call.",
].join("\n");

export const LIST_TAGS_DESCRIPTION = [
  "Return the live tag inventory for a workspace. Use this when you need to know exactly which `#tag-name` markers parse_tags will currently recognize — for example when the user asks 'what tags do I have', when debugging unexpected (non-)expansion, or before recommending a tag.",
  "",
  "Each entry includes the normalized tag key (lowercase, hyphens) and its origin scope:",
  "- 'builtin'   — bundled with @agent-tags/mcp",
  "- 'global'    — ~/.agents/tags",
  "- 'workspace' — <workspace>/.agents/tags",
  "",
  "Workspace tags override global, which override builtin; the returned `source` reflects which definition won.",
  "",
  "INPUTS:",
  "- workspace (optional): absolute path to the user's project root. When omitted, the server-startup workspace is used.",
  "",
  "OUTPUT:",
  "- tags: array of { key, source }, sorted by key.",
  "",
  "BOUNDARY:",
  "- Does not return tag bodies. Use show_tag for that.",
  "- Does not change which tags parse_tags recognizes; this is read-only inspection.",
].join("\n");

export const SHOW_TAG_DESCRIPTION = [
  "Return the body of a single tag from the live registry. Use this to inspect what `#name` will actually expand into — for verifying behavior, debugging, or reviewing a tag's content without rewriting a full prompt.",
  "",
  "Names are normalized the same way parse_tags normalizes them: lowercased, underscores collapsed to hyphens, optional leading '#' is stripped. So 'deny', '#deny', 'DENY', and 'de_ny' all resolve to the same definition.",
  "",
  "INPUTS:",
  "- name: the tag to look up (e.g. 'explore', '#explore', 'tag_name').",
  "- workspace (optional): absolute path to the user's project root. When omitted, the server-startup workspace is used.",
  "",
  "OUTPUT:",
  "- found: whether the tag is currently loaded.",
  "- tag (when found): { key, rawName, body, source, sourcePath } — `source` is one of 'builtin' | 'global' | 'workspace', `sourcePath` is the underlying location used to resolve it.",
  "",
  "BOUNDARY:",
  "- Returns one tag at a time. Use list_tags for the full inventory.",
  "- Read-only; does not modify any tag file.",
].join("\n");

export const CREATE_TAG_GUIDE = [
  "# Creating Tags",
  "",
  "## Overview",
  "",
  "Tags are proactive, composable, minimized agent directions. Use them as intent amplifiers: a tag should annotate one local part of a prompt with one atomic intent.",
  "",
  "Skills and commands govern broader workflows. Tags provide precise, human-called control inside the prompt, exactly where the user writes `#tag-name`.",
  "",
  "## When to Use",
  "",
  "Create or edit a tag when the user wants to reuse a small prompt annotation such as:",
  "",
  "- `#fyi` for information that should not cause over-response",
  "- `#explore` for local codebase investigation",
  "- `#example` for non-exhaustive examples that imply a broader pattern",
  "- `#btw` for low-salience side notes",
  "- A project-specific convention, domain hint, or repeated instruction that should compose with other tags",
  "",
  "Do not create a tag for a full multi-turn workflow. Use an agent skill, slash command, or other workflow primitive for that.",
  "",
  "## Tag Anatomy",
  "",
  "A tag is a plain `.md` or `.txt` file. The filename is the tag name. The entire file content is the tag body.",
  "",
  "Locations:",
  "",
  "| Scope | Path | Behavior |",
  "| --- | --- | --- |",
  "| Global | `~/.agents/tags/<tag-name>.md` | Available across workspaces |",
  "| Workspace | `<workspace>/.agents/tags/<tag-name>.md` | Available only in that workspace; overrides global |",
  "",
  "Naming:",
  "",
  "- Start with a letter.",
  "- Use letters, numbers, hyphens, or underscores.",
  "- Prefer kebab-case: `deep-debug.md`.",
  "- `#tag_name` and `#tag-name` resolve to the same tag key.",
  "",
  "Current parser limits:",
  "",
  "- No YAML frontmatter parsing. Do not add frontmatter to tag files.",
  "- No semantic Markdown parsing. Headings are just body text.",
  "- Keep ordinary tags under about 600 characters.",
  "- Tags in inline code spans and triple-backtick code fences are not expanded.",
  "- Tag bodies are currently expanded one pass; do not rely on nested `#other-tag` references unless recursive expansion is explicitly supported.",
  "",
  "## Core Pattern",
  "",
  "Write the body as direct instructions to the agent. Define the trigger, the behavior, the evidence or output expected, and one boundary.",
  "",
  "Good tag body:",
  "",
  "```markdown",
  "This is a non-exhaustive demonstration set. Infer the underlying pattern from the examples and surrounding context: naming conventions, structure, domain logic, and codebase evidence. Propose the complete relevant set. Mark inferred items distinctly from user-provided examples. Do not treat the examples as a closed list unless the user says they are exhaustive.",
  "```",
  "",
  "Bad tag body:",
  "",
  "```markdown",
  "---",
  "name: example",
  "requires: [explore, systematic-debugging]",
  "recursive: true",
  "---",
  "",
  "# Example Tag",
  "",
  "Use many steps, templates, sections, completion criteria, and long workflow rules...",
  "```",
  "",
  "Why bad: the parser treats metadata and headings as literal tag body, not configuration. Long workflow rules do not belong in tags.",
  "",
  "## Quick Reference",
  "",
  "| Do | Avoid |",
  "| --- | --- |",
  "| One atomic intent | Bundled workflow with many phases |",
  "| Short imperative body | Long tutorial or checklist |",
  "| Local annotation semantics | Whole-conversation command semantics |",
  '| Clear output/evidence expectation | Vague "be better" guidance |',
  "| One explicit boundary | Unsupported metadata or dependency fields |",
  "| Smoke-test with `parse_tags` | Assuming the client loaded it dynamically |",
  "",
  "## Writing Checklist",
  "",
  "1. Choose the smallest reusable intent.",
  "2. Pick a kebab-case filename under the correct tags directory.",
  "3. Write only the tag body; no frontmatter.",
  "4. Keep the body concise and composable with other tags.",
  "5. Include what to do and what not to overdo.",
  "6. Smoke-test with `parse_tags` using a prompt that contains `#tag-name`.",
  "",
  "## Common Mistakes",
  "",
  "**Mistake: Writing a workflow as a tag.**  ",
  "If the instruction needs phases, tools, verification gates, or multi-turn discipline, do not make it a tag. A tag should be a local intent annotation.",
  "",
  "**Mistake: Adding YAML metadata.**  ",
  "Tags do not parse frontmatter yet. Metadata becomes literal instruction text and can confuse the agent.",
  "",
  "**Mistake: Making one tag depend on another.**  ",
  "Prefer composing tags in the user prompt: `#example #explore`. Do not hide required composition inside a tag body unless recursive expansion is implemented and documented.",
  "",
  "**Mistake: Making the tag too broad.**  ",
  "`#careful` is vague. `#verify-output-shape` or `#infer-examples` gives the agent a concrete intent.",
  "",
  "## Smoke Test",
  "",
  "After writing `<workspace>/.agents/tags/infer-examples.md`, test:",
  "",
  "```text",
  "Create handlers for auth, billing, notifications, etc. #infer-examples",
  "```",
  "",
  "Expected behavior: `parse_tags` prepends an `<infer-examples>...</infer-examples>` block and replaces the inline marker with `<infer-examples/>` while preserving the rest of the prompt.",
].join("\n");
