// Server instructions are unreliable in practice — many clients (OpenCode confirmed)
// drop them entirely. The full picture lives in per-tool descriptions and resource
// metadata, which clients render reliably. Keep this string short and meta-cognitive.
export const SERVER_INSTRUCTIONS = [
  "This MCP server exposes tag and skill capabilities for agent-tags. Tool and resource",
  "descriptions are authoritative — query them at runtime rather than relying on this",
  "instruction block, which some clients drop entirely.",
  "",
  "Calling rules:",
  "- The tag set is dynamic. Definitions live under `~/.agents/tags` (global) and",
  "  `<workspace>/.agents/tags` (project) and may change between turns. Use the live tool",
  "  and resource surface, not baked-in knowledge.",
  "- `#tag-name` and `#tag_name` resolve to the same tag.",
].join("\n");

export const PARSE_TAGS_DESCRIPTION = [
  'Expand inline `#tag` markers (e.g. `#explore`, `#fyi`, `#example`, `#btw`, `#deny`) in a user prompt into XML directives. For each recognized `#name` in prose, the tool injects `<name>...body...</name>` once at the top of the rewritten prompt and replaces each `#name` with a self-closing `<name/>` at its original location. The marker can sit anywhere — opening (`#btw the previous...`), middle (`...handles `#tag_name` resolution...`), end (`...check the regex specifics #explore`), or scattered across multiple clauses. Tags inside fenced code blocks (```) and inline code spans (`) are preserved verbatim. Unknown `#tags` (no matching definition) pass through unchanged. `#tag_name` and `#tag-name` resolve to the same definition. Returns the literal sentinel "(no tags found)" when no recognized `#tag` markers appear in prose.',
  "",
  "EXAMPLES:",
  "",
  "  user: ok thanks, continue",
  '  call: parse_tags({ prompt: "ok thanks, continue" })',
  "  result: (no tags found)",
  "",
  "  user: walk me through how the prompt rewriter handles edge cases #explore",
  '  call: parse_tags({ prompt: "walk me through how the prompt rewriter handles edge cases #explore" })',
  "  result:",
  "    <explore>...explore body...</explore>",
  "",
  "    walk me through how the prompt rewriter handles edge cases <explore/>",
  "",
  "  user: explain how this server discovers tag definitions",
  '  call: parse_tags({ prompt: "explain how this server discovers tag definitions" })',
  "  result: (no tags found)",
  "",
  "  user: what's the #deny tag for?",
  '  call: parse_tags({ prompt: "what\'s the #deny tag for?" })',
  "  result:",
  "    <deny>...deny body...</deny>",
  "",
  "    what's the <deny/> tag for?",
  "",
  "  user: Compare FilesystemTagSource and MergedTagSource #explore. The merging behavior #fyi is intentional.",
  '  call: parse_tags({ prompt: "Compare FilesystemTagSource and MergedTagSource #explore. The merging behavior #fyi is intentional." })',
  "  result:",
  "    <explore>...explore body...</explore>",
  "    <fyi>...fyi body...</fyi>",
  "",
  "    Compare FilesystemTagSource and MergedTagSource <explore/>. The merging behavior <fyi/> is intentional.",
  "",
  "  user: just answer directly, no tools — what's the difference between #fyi and #btw?",
  '  call: parse_tags({ prompt: "just answer directly, no tools — what\'s the difference between #fyi and #btw?" })',
  "  result:",
  "    <fyi>...fyi body...</fyi>",
  "    <btw>...btw body...</btw>",
  "",
  "    just answer directly, no tools — what's the difference between <fyi/> and <btw/>?",
  "",
  "  user: add a tag for discarding objects (file/function/modules etc. #example)",
  '  call: parse_tags({ prompt: "add a tag for discarding objects (file/function/modules etc. #example)" })',
  "  result:",
  "    <example>...example body...</example>",
  "",
  "    add a tag for discarding objects (file/function/modules etc. <example/>)",
  "",
  "  user (code fence with tag inside):",
  "    ```",
  "    # comment containing #fyi",
  "    ```",
  "    what does the snippet do?",
  "  call: parse_tags({ prompt: <verbatim including the code fence> })",
  "  result: (no tags found)        # tags inside code fences are escape hatches, not directives",
  "",
  "  user: explain the `TAG_REGEX` const, reference it with #explore",
  '  call: parse_tags({ prompt: "explain the `TAG_REGEX` const, reference it with #explore" })',
  "  result:",
  "    <explore>...explore body...</explore>",
  "",
  "    explain the `TAG_REGEX` const, reference it with <explore/>",
  "",
  "  user: I want to use #somemadeuptagname here",
  '  call: parse_tags({ prompt: "I want to use #somemadeuptagname here" })',
  "  result: I want to use #somemadeuptagname here     # unknown tag passes through unchanged, no header injected",
  "",
  "  user: in promptRewriter.ts, what's the difference between how line 70 detects fenced code blocks versus how line 96 detects inline backticks? include the regex/string-matching specifics #explore",
  '  call: parse_tags({ prompt: "in promptRewriter.ts, what\'s the difference between how line 70 detects fenced code blocks versus how line 96 detects inline backticks? include the regex/string-matching specifics #explore" })',
  "  result:",
  "    <explore>...explore body...</explore>",
  "",
  "    in promptRewriter.ts, what's the difference between how line 70 detects fenced code blocks versus how line 96 detects inline backticks? include the regex/string-matching specifics <explore/>",
  "  # long, technically dense prompts still get parsed first — the visual weight of the question doesn't change the routine",
  "",
  "  user: #btw the previous test session was useful — now show me how `BuiltinTagSource` is wired into the merged source chain, and infer where future remote sources would plug in #example",
  '  call: parse_tags({ prompt: "#btw the previous test session was useful — now show me how `BuiltinTagSource` is wired into the merged source chain, and infer where future remote sources would plug in #example" })',
  "  result:",
  "    <btw>...btw body...</btw>",
  "    <example>...example body...</example>",
  "",
  "    <btw/> the previous test session was useful — now show me how `BuiltinTagSource` is wired into the merged source chain, and infer where future remote sources would plug in <example/>",
  "  # multiple tags across one prompt are all parsed in a single call; conversational lead-ins (`#btw`) and substantive directives (`#example`) coexist",
  "",
  "  user: now look at how `MergedTagSource.get()` resolves collisions between global and workspace tags, then explain why `BuiltinTagSource` ends up at the start of the source array even though it's the lowest precedence #explore",
  '  call: parse_tags({ prompt: "now look at how `MergedTagSource.get()` resolves collisions between global and workspace tags, then explain why `BuiltinTagSource` ends up at the start of the source array even though it\'s the lowest precedence #explore" })',
  "  result:",
  "    <explore>...explore body...</explore>",
  "",
  "    now look at how `MergedTagSource.get()` resolves collisions between global and workspace tags, then explain why `BuiltinTagSource` ends up at the start of the source array even though it's the lowest precedence <explore/>",
  "  # multi-clause technical asks with a trailing tag still trigger the call before any code is read; the routine fires regardless of how the prompt opens",
  "",
  "INPUTS:",
  "- prompt: the user's verbatim message for the turn. Pass it unmodified — the rewriter relies on the literal text, including code fences and inline code spans, to decide what to expand and what to preserve.",
  "- workspace (optional): absolute path to the user's project root. Used to load workspace-scoped tag definitions (which override global tags on name collision). When omitted, the server-startup workspace is used.",
  "",
  "OUTPUT:",
  "- For tag-bearing prompts: the rewritten prompt with `<name>...body...</name>` directive blocks prepended and `<name/>` placeholders in prose at the original locations. Each `<name/>` directive applies at the location it appears, not globally.",
  '- For tag-free prompts: the literal sentinel string "(no tags found)".',
  "- For prompts with only unknown `#tags`: the prompt is returned unchanged, with the `#name` markers preserved verbatim.",
  "",
  "BOUNDARY:",
  "- The tool's rewritten output is the single source of truth for tag bodies. Read the injected `<name>...body...</name>` content rather than guessing what each `#name` means based on its label alone.",
  "- The presence, position, or visual weight of a `#tag` does not change the routine — `#explore` at the end of a long technical question, `#btw` opening a casual aside, `#fyi` mid-clause, and `#somemadeup` (unknown) all flow through the same call.",
].join("\n");

export const LIST_TAGS_DESCRIPTION = [
  "Return the live tag inventory for a workspace. Use this when you need to know exactly which `#tag-name` markers parse_tags will currently recognize — for example when the user asks 'what tags do I have', when debugging unexpected (non-)expansion, or before recommending a tag.",
  "",
  "Each entry includes the normalized tag key (lowercase, hyphens) and its origin scope:",
  "- 'builtin'   — bundled with @agent-tags/mcp",
  "- 'global'    — ~/.agents/tags",
  "- 'workspace' — <workspace>/.agents/tags",
  "",
  "Workspace tags override global, which override builtin; the returned `source` reflects which definition won.",
  "",
  "INPUTS:",
  "- workspace (optional): absolute path to the user's project root. When omitted, the server-startup workspace is used.",
  "",
  "OUTPUT:",
  "- tags: array of { key, source }, sorted by key.",
  "",
  "BOUNDARY:",
  "- Does not return tag bodies. Use show_tag for that.",
  "- Does not change which tags parse_tags recognizes; this is read-only inspection.",
  "",
  "FALLBACK NOTE:",
  "- This tool is the canonical fallback for clients that do not expose MCP resources to the model. If your client supports MCP resources, the same data is available via `resources/list` (inventory) and `resources/read` (single tag body). Resources also surface in `@`-mention pickers in compatible UIs. Prefer resources when available; reach for this tool when they are not.",
].join("\n");

export const SHOW_TAG_DESCRIPTION = [
  "Return the body of a single tag from the live registry. Use this to inspect what `#name` will actually expand into — for verifying behavior, debugging, or reviewing a tag's content without rewriting a full prompt.",
  "",
  "Names are normalized the same way parse_tags normalizes them: lowercased, underscores collapsed to hyphens, optional leading '#' is stripped. So 'deny', '#deny', 'DENY', and 'de_ny' all resolve to the same definition.",
  "",
  "INPUTS:",
  "- name: the tag to look up (e.g. 'explore', '#explore', 'tag_name').",
  "- workspace (optional): absolute path to the user's project root. When omitted, the server-startup workspace is used.",
  "",
  "OUTPUT:",
  "- found: whether the tag is currently loaded.",
  "- tag (when found): { key, rawName, body, source, sourcePath } — `source` is one of 'builtin' | 'global' | 'workspace', `sourcePath` is the underlying location used to resolve it.",
  "",
  "BOUNDARY:",
  "- Returns one tag at a time. Use list_tags for the full inventory.",
  "- Read-only; does not modify any tag file.",
  "",
  "FALLBACK NOTE:",
  "- This tool is the canonical fallback for clients that do not expose MCP resources to the model. If your client supports MCP resources, the same data is available via `resources/list` (inventory) and `resources/read` (single tag body). Resources also surface in `@`-mention pickers in compatible UIs. Prefer resources when available; reach for this tool when they are not.",
].join("\n");

export const PARSE_SKILL_TAGS_DESCRIPTION = [
  "Load an Agent Skill from an absolute filesystem path and return its body with any inline `#tag` markers expanded against a skill-local tag source. Use this whenever you load a skill — even if your runtime has its own skill loader. The returned body is what should drive the skill's behavior, with any `<tag-name/>` directives in place.",
  "",
  "INPUTS:",
  "- path: absolute filesystem path to the skill's `SKILL.md`. The host agent already knows where its skill files live; pass the path verbatim. Relative paths are rejected.",
  "- useBuiltinTags (optional, default true): include built-in tags (`#fyi`, `#explore`, `#example`, `#use-skill`, `#btw`) in the skill-local source. Set to false for strict isolation.",
  "",
  "OUTPUT:",
  "- found: true if the SKILL.md was loaded; false if the path is missing, unreadable, or relative.",
  "- skill (when found): { path, name, description, body, hasBundledTags, expanded }. `body` is the SKILL.md content with frontmatter stripped, and with `#tag` markers rewritten as `<tag/>` placeholders preceded by `<tag>...body...</tag>` headers when the body contained any. `expanded` is true iff rewriting occurred.",
  "",
  "BEHAVIOR:",
  "- Tag isolation is guaranteed. The skill-local tag source includes ONLY (a) the bundled tags shipped at `<dirname(path)>/tags/*.{md,txt}` and (b) the five built-in tags (when `useBuiltinTags` is true). User-defined global and workspace tags are intentionally NOT visible to skill bodies — this prevents user tag conventions from contaminating skill semantics.",
  "- Skill-bundled tags shadow built-ins of the same name within that skill's expansion only.",
  "- Frontmatter is stripped from the body before tag expansion. Frontmatter fields (e.g. `name`, `description`) are extracted into the structured response but are NOT part of the body.",
  "",
  "WHY THIS TOOL EXISTS:",
  "- The host agent already discovers skills through its own conventions (`.agents/skills/`, `.claude/skills/`, `.cursor/skills/`, etc.). This tool does not re-discover them. Its value is tag-aware parsing of the SKILL.md body, which the agent's native skill loader does not perform.",
  "- If you have already loaded a skill through another path and notice `#tag` markers in its body, re-call this tool with the same `path` to obtain the expanded version.",
  "",
  "BOUNDARY:",
  "- Path-only by design. There is no `name` argument. The agent owns discovery; this tool owns parsing.",
  "- Returns only the SKILL.md body. Companion files (`scripts/`, `references/`, `assets/`) are NOT read by this tool.",
  "- Missing or unreadable path returns `{ found: false }` rather than throwing.",
].join("\n");

export const CREATE_TAG_GUIDE = [
  "# Creating Tags",
  "",
  "## Overview",
  "",
  "Tags are proactive, composable, minimized agent directions. Use them as intent amplifiers: a tag should annotate one local part of a prompt with one atomic intent.",
  "",
  "Skills and commands govern broader workflows. Tags provide precise, human-called control inside the prompt, exactly where the user writes `#tag-name`.",
  "",
  "## When to Use",
  "",
  "Create or edit a tag when the user wants to reuse a small prompt annotation such as:",
  "",
  "- `#fyi` for information that should not cause over-response",
  "- `#explore` for local codebase investigation",
  "- `#example` for non-exhaustive examples that imply a broader pattern",
  "- `#btw` for low-salience side notes",
  "- A project-specific convention, domain hint, or repeated instruction that should compose with other tags",
  "",
  "Do not create a tag for a full multi-turn workflow. Use an agent skill, slash command, or other workflow primitive for that.",
  "",
  "## Tag Anatomy",
  "",
  "A tag is a plain `.md` or `.txt` file. The filename is the tag name. The entire file content is the tag body.",
  "",
  "Locations:",
  "",
  "| Scope | Path | Behavior |",
  "| --- | --- | --- |",
  "| Global | `~/.agents/tags/<tag-name>.md` | Available across workspaces |",
  "| Workspace | `<workspace>/.agents/tags/<tag-name>.md` | Available only in that workspace; overrides global |",
  "",
  "Naming:",
  "",
  "- Start with a letter.",
  "- Use letters, numbers, hyphens, or underscores.",
  "- Prefer kebab-case: `deep-debug.md`.",
  "- `#tag_name` and `#tag-name` resolve to the same tag key.",
  "",
  "Current parser limits:",
  "",
  "- Optional YAML frontmatter is permitted but not required. All fields are optional. The body of the tag is whatever follows the closing `---`. Tags without frontmatter are treated as body-only (existing behavior).",
  "- Frontmatter fields are not interpreted by the parser today. They serve as author-facing metadata only (e.g., notes, version markers, audience hints).",
  "- No semantic Markdown parsing. Headings are just body text.",
  "- Keep ordinary tags under about 600 characters.",
  "- Tags in inline code spans and triple-backtick code fences are not expanded.",
  "- Tag bodies are currently expanded one pass; do not rely on nested `#other-tag` references unless recursive expansion is explicitly supported.",
  "",
  "## Skill-Bundled Tags",
  "",
  "Skills can ship their own tags under `<skill-dir>/tags/*.{md,txt}`. These tags are scoped to the skill — they are NOT visible to the user's global or workspace tag inventory, and they do NOT shadow tags with the same name elsewhere.",
  "",
  "When `parse_skill_tags` loads a skill, the skill's own tag vocabulary is composed with the built-in tags only. Skill authors can therefore rely on the following built-in tags being available inside their skill bodies:",
  "",
  "- `#fyi` — accept information silently",
  "- `#explore` — investigate locally",
  "- `#example` — non-exhaustive demonstration set",
  "- `#use-skill` — load a relevant skill",
  "- `#btw` — incidental aside",
  "",
  "User-defined global and workspace tags are intentionally not visible to skill bodies. This isolation prevents user tag conventions from contaminating skill semantics.",
  "",
  "A skill-bundled tag with the same name as a built-in shadows the built-in within that skill's expansion only.",
  "",
  "",
  "## Core Pattern",
  "",
  "Write the body as direct instructions to the agent. Define the trigger, the behavior, the evidence or output expected, and one boundary.",
  "",
  "Good tag body:",
  "",
  "```markdown",
  "This is a non-exhaustive demonstration set. Infer the underlying pattern from the examples and surrounding context: naming conventions, structure, domain logic, and codebase evidence. Propose the complete relevant set. Mark inferred items distinctly from user-provided examples. Do not treat the examples as a closed list unless the user says they are exhaustive.",
  "```",
  "",
  "Bad tag body:",
  "",
  "```markdown",
  "---",
  "name: example",
  "requires: [explore, systematic-debugging]",
  "recursive: true",
  "---",
  "",
  "# Example Tag",
  "",
  "Use many steps, templates, sections, completion criteria, and long workflow rules...",
  "```",
  "",
  "Why bad: the parser treats metadata and headings as literal tag body, not configuration. Long workflow rules do not belong in tags.",
  "",
  "## Quick Reference",
  "",
  "| Do | Avoid |",
  "| --- | --- |",
  "| One atomic intent | Bundled workflow with many phases |",
  "| Short imperative body | Long tutorial or checklist |",
  "| Local annotation semantics | Whole-conversation command semantics |",
  '| Clear output/evidence expectation | Vague "be better" guidance |',
  "| One explicit boundary | Unsupported metadata or dependency fields |",
  "| Smoke-test with `parse_tags` | Assuming the client loaded it dynamically |",
  "",
  "## Writing Checklist",
  "",
  "1. Choose the smallest reusable intent.",
  "2. Pick a kebab-case filename under the correct tags directory.",
  "3. Write only the tag body; no frontmatter.",
  "4. Keep the body concise and composable with other tags.",
  "5. Include what to do and what not to overdo.",
  "6. Smoke-test with `parse_tags` using a prompt that contains `#tag-name`.",
  "",
  "## Common Mistakes",
  "",
  "**Mistake: Writing a workflow as a tag.**  ",
  "If the instruction needs phases, tools, verification gates, or multi-turn discipline, do not make it a tag. A tag should be a local intent annotation.",
  "",
  "",
  "**Mistake: Making one tag depend on another.**  ",
  "Prefer composing tags in the user prompt: `#example #explore`. Do not hide required composition inside a tag body unless recursive expansion is implemented and documented.",
  "",
  "**Mistake: Making the tag too broad.**  ",
  "`#careful` is vague. `#verify-output-shape` or `#infer-examples` gives the agent a concrete intent.",
  "",
  "## Smoke Test",
  "",
  "After writing `<workspace>/.agents/tags/infer-examples.md`, test:",
  "",
  "```text",
  "Create handlers for auth, billing, notifications, etc. #infer-examples",
  "```",
  "",
  "Expected behavior: `parse_tags` prepends an `<infer-examples>...</infer-examples>` block and replaces the inline marker with `<infer-examples/>` while preserving the rest of the prompt.",
].join("\n");
